### ISSUE TITLE
Setting up routes

### ISSUE THREAD

**Issue by Curtismn87** [ga-dc/pbj-project3#11]
We are unable to get handlebars to render an index page.
our app.js looks like this:

```
var express = require("express");
var app = express();
var path = require("path");
var bodyParser = require("body-parser");

app.use(bodyParser.json());
app.use("/", express.static(path.join(__dirname + "/")));
app.set("view engine", "hbs");

app.get("/", function(req, res){
  res.render("/");
});
```

We are getting the error: 

```
Error: Failed to lookup view "/app/views/index" in views directory "/Users/curtismn87/WDI/projects/MyStox/views"
```

The file name is not "/Users/curtismn87/WDI/projects/MyStox/views" ... the view is in "MyStox/app/views"

**Comment by RobertAKARobin** [comment]
Change this line:

```
app.use("/", express.static(path.join(__dirname + "/")));
```

To this:

```
app.use("/", express.static(path.join(__dirname + "/app")));
```

**Comment by Curtismn87** [comment]
Still looking in the same /MyStox/views path. We even tried /kanyeWest and it doesn't change that path.

**Comment by RobertAKARobin** [comment]
Oh. It's because you're telling it to "render /". So it's looking for a file called "/". Presumably, that file doesn't exist! If you want it to render a specific view, say, one called "kanye.hbs", you'd write `res.render("app/views/kanye")`.

See here:

https://github.com/ga-dc/tunr_node_hbs/blob/master/controllers/artists.js

If you want to render just a regular HTML file, you'd use something like this:

```
res.sendFile(__dirname + "/app/views/kanye.html");
```

**Comment by Curtismn87** [comment]
And that worked! we had the file as kanye.hbs instead of kanye.html so when we tried sendFile at first it was just every piece of text in the kanye.hbs... (P.S. we're not actually using kanye). But thanks!

**Comment by RobertAKARobin** [comment]
Wouldn't judge you if you were using Kanye.

Kanye is love. Kanye is life.
